### PR TITLE
MAMMAM looks promising

### PR DESCRIPTION
**Pull request by bastianalbers**
MAMMAM looks promising

### CODE REVIEW

**Comment by sto3psl** [comment]
Please add a test 🤓

**Comment by klaemo** [comment]
`/kick @sto3psl`

**Comment by sto3psl** [comment]
Why am I still watching this repository? 😂

**Comment by bastianalbers** [comment]
We haven't tested that Restaurant yet, but afterwards we'll add a test.

**Comment by bastianalbers** [comment]
bildschirmfoto 2019-01-28 um 16 42 00
🤔

**Comment by bastianalbers** [comment]
I think this is our open invitation for @sto3psl to join us for lunch :D

**Comment by sto3psl** [comment]
> /kick @sto3psl

Well this @klaemo guy seemed to dislike my thoughtful review.

**Pull request merged**
